## Attempt - 2
Here I try to convert 'strings' dtype to one-hot vectors and try to make a CNN clasifier.
Following -https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers This example

Do read README.md/ipynb  file

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [5]:
import pathlib

In [6]:
dataframe = pd.read_csv('Test_ag.csv')
dataframe.head()


author                                              title  year  \
0  Ajay Gupta                 Explanation-based Failure Recovery  1987   
1  Ajay Gupta       Time Representation Prolog Circuit Modelling  1991   
2  Ajay Gupta       Optimal Deployment Triggers Detecting Events  2004   
3  Ajay Gupta                      Web Page Ranking Based Events  2004   
4  Ajay Gupta  AGATHA: An Integrated Expert System Test Diagn...  1991   

                                             authors   jconf     pid  label  
0                                         Ajay Gupta    AAAI   13048      0  
1           Yossi Lichtenstein,Bob Welham,Ajay Gupta   ALPUK   39153      0  
2  Manish Bhide,Ajay Gupta,Mukul Joshi,Mukesh K. ...    DEXA  149270      2  
3          Ajay Gupta,Manish Bhide,Mukesh K. Mohania  EC-Web  175996      2  
4  Daryl Allred,Yossi Lichtenstein,Chris Preist,M...    IAAI  258611      0

In [7]:
dataframe.pop('author')
dataframe = dataframe.where(dataframe.notnull(), 'U')
dataframe.isna()
dataframe.tail(-5)

title  year  \
5   Management Conflicting Obligations Self-Protec...  2005   
6           Policy Framework Autonomic Data Managemen  2004   
7   Using Lagrangean Relaxation Service Location P...  2008   
8   Mobility-Pattern-Based Anomaly Detection Algor...  2008   
9   Detection Masquerade Attacks Wireless Sensor N...  2007   
10   Dynamic Access Control Framework Based On Events  2003   
11  Towards Bringing Database Management Task Real...  2003   
12               Enhanced Business Intelligence EROCS  2008   
13            Hardware Diagnosis as Program Debugging  1987   
14                Efficient Design Boltzmann Machines  1990   
15                  Policy Driven Data Administration  2002   
16                   Clustering short texts wikipedia  2007   
17  LIPTUS: associating structured unstructured in...  2007   
18        Retaining personal expression social search  2009   
19                Some issues privacy data management  2007   
20                       Mutual Exclusion a Hypercube  1993   
21  Multivariate Integration Hypercubic Mesh Networks  1998   
22  Power Consumption Analysis Maximum A Posterior...  2008   
23  IT Infrastructure Emerging Markets: Arguing En...  2006   
24  Power Efficient Algorithms Computing Fast Four...  2006   
25   Enabling analysts managed services CRM analytics  2009   
26                   Document Summarization Wikipedia  2009   
27   Performance Indicators a 802.11 WLAN Deployment.  2009   
28  Towards Automated Privacy Compliance Informati...  2008   
29  Simulation Detection Self-Propagating Worms Vi...  2008   
30  A workstation's communication performance benc...  1996   
31                Synchronization distributed systems  1989   
32  Largeandmdash;scale parallel numerical integra...  1999   
33  A method efficient design Boltzmann machines c...  1990   
34  On complexity computation learning neural netw...  1991   
35    Hack I.T.: security through penetration testing  2002   

                                              authors  \
5   Rema Ananthanarayanan,Mukesh K. Mohania,Ajay G...   
6   Manish Bhide,Ajay Gupta,Mukul Joshi,Mukesh K. ...   
7       Zill-E-Huma Kamal,Ala I. Al-Fuqaha,Ajay Gupta   
8                               Chaoli Cai,Ajay Gupta   
9             Vijay Bhuse,Ajay Gupta,Ala I. Al-Fuqaha   
10  Manish Bhide,Sandeep Pandey,Ajay Gupta,Mukesh ...   
11          Ajay Gupta,Manish Bhide,Mukesh K. Mohania   
12  Manish Bhide,V. Chakravarthy,Ajay Gupta,Himans...   
13                                         Ajay Gupta   
14                          Ajay Gupta,Wolfgang Maass   
15  Vishal S. Batra,Jaijit Bhattacharya,Harish Cha...   
16    Somnath Banerjee,Krishnan Ramanathan,Ajay Gupta   
17  Manish Bhide,Ajay Gupta,Rahul Gupta,Prasan Roy...   
18                         Praphul Chandra,Ajay Gupta   
19  Mukesh K. Mohania,Rema Ananthanarayanan,Ajay G...   
20          Ajay Gupta,Steven C. Bruell,Sukumar Ghosh   
21                     Elise de Doncker,Ajay K. Gupta   
22  Zill-E-Huma Kamal,Ajay Gupta,Ashfaq A. Khokhar...   
23  Ajay Gupta,Parthasarathy Ranganathan,Prashant ...   
24            Turkmen Canli,Ajay Gupta,Ashfaq Khokhar   
25  Indrajit Bhattacharya,Shantanu Godbole,Ajay Gu...   
26  Krishnan Ramanathan,Yogesh Sankarasubramaniam,...   
27                         Ajay Gupta,Prabhash Dhyani   
28    Rema Ananthanarayanan,Ajay Gupta,Mukesh Mohania   
29                                         Ajay Gupta   
30                  Kurt Maly,Ajay Gupta,Satish Mynam   
31                                         Ajay Gupta   
32        Elise de Doncker,Ajay Gupta,Rodger R. Zanny   
33                          Ajay Gupta,Wolfgang Maass   
34                                         Ajay Gupta   
35         T. J. Klevinsky,Scott Laliberte,Ajay Gupta   

                                                jconf      pid  label  
5                                                ICAC   264268      2  
6                                                ICAC   264291

In [39]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
# print(len(train), 'train examples')
# print(len(val), 'validation examples')
test.to_dict(orient='records')

[{'title': 'Multivariate Integration Hypercubic Mesh Networks',
  'year': 1998,
  'authors': 'Elise de Doncker,Ajay K. Gupta',
  'jconf': 'Parallel Computing',
  'pid': 1034401,
  'label': 4},
 {'title': 'Simulation Detection Self-Propagating Worms Viruses',
  'year': 2008,
  'authors': 'Ajay Gupta',
  'jconf': 'U',
  'pid': 1393934,
  'label': 6},
 {'title': 'IT Infrastructure Emerging Markets: Arguing End-to-End Perspective',
  'year': 2006,
  'authors': 'Ajay Gupta,Parthasarathy Ranganathan,Prashant Sarin,Mehul A. Shah',
  'jconf': 'IEEE Pervasive Computing',
  'pid': 1179332,
  'label': 0},
 {'title': 'Enabling analysts managed services CRM analytics',
  'year': 2009,
  'authors': 'Indrajit Bhattacharya,Shantanu Godbole,Ajay Gupta,Ashish Verma,Jeff Achtermann,Kevin English',
  'jconf': 'KDD',
  'pid': 1212517,
  'label': 2},
 {'title': 'Management Conflicting Obligations Self-Protecting Policy-Based Systems',
  'year': 2005,
  'authors': 'Rema Ananthanarayanan,Mukesh K. Mohania,Aja

In [9]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('label')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  ds = ds.prefetch(batch_size)
  return ds

In [10]:
batch_size = 5
train_ds = df_to_dataset(train, batch_size=batch_size)

In [11]:
[(train_features, label_batch)] = train_ds.take(1)
print('Every feature:', list(train_features.keys()))
print('A batch of ages:', train_features['title'])
print('A batch of targets:', label_batch )

Every feature: ['title', 'year', 'authors', 'jconf', 'pid']
A batch of ages: tf.Tensor(
[b'Retaining personal expression social search'
 b'Power Efficient Algorithms Computing Fast Fourier Transform over Wireless Sensor Networks'
 b'Efficient Design Boltzmann Machines'
 b'Enabling analysts managed services CRM analytics'
 b'On complexity computation learning neural networks'], shape=(5,), dtype=string)
A batch of targets: tf.Tensor([0 4 7 2 7], shape=(5,), dtype=int64)


In [12]:
def get_normalization_layer(name, dataset):
  # Create a Normalization layer for our feature.
  normalizer = preprocessing.Normalization(axis=None)

  # Prepare a Dataset that only yields our feature.
  feature_ds = dataset.map(lambda x, y: x[name])

  # Learn the statistics of the data.
  normalizer.adapt(feature_ds)

  return normalizer

In [13]:
photo_count_col = train_features['year']
layer = get_normalization_layer('year', train_ds)
layer(photo_count_col)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 1.0981017 ],
       [ 0.68863785],
       [-1.4951699 ],
       [ 1.0981017 ],
       [-1.3586818 ]], dtype=float32)>

In [14]:
def get_category_encoding_layer(name, dataset, dtype, max_tokens=None):
  # Create a StringLookup layer which will turn strings into integer indices
  if dtype == 'string':
    index = preprocessing.StringLookup(max_tokens=max_tokens)
  else:
    index = preprocessing.IntegerLookup(max_tokens=max_tokens)

  # Prepare a Dataset that only yields our feature
  feature_ds = dataset.map(lambda x, y: x[name])

  # Learn the set of possible values and assign them a fixed integer index.
  index.adapt(feature_ds)

  # Create a Discretization for our integer indices.
  encoder = preprocessing.CategoryEncoding(num_tokens=index.vocabulary_size())

  # Apply one-hot encoding to our indices. The lambda function captures the
  # layer so we can use them, or include them in the functional model later.
  return lambda feature: encoder(index(feature))

In [15]:
type_col = train_features['title']
layer = get_category_encoding_layer('title', train_ds, 'string')
layer(type_col)

<tf.Tensor: shape=(5, 24), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [16]:
type_col = train_features['authors']
author_encoding_layer = get_category_encoding_layer('authors', train_ds,
                                                      'string')
author_encoding_layer(type_col)

<tf.Tensor: shape=(5, 21), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]], dtype=float32)>

In [17]:
type_col = train_features['jconf']
jconf_encoding_layer = get_category_encoding_layer('jconf', train_ds,
                                                      'string')
jconf_encoding_layer(type_col)

<tf.Tensor: shape=(5, 21), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
type_col = train_features['pid']
pid_encoding_layer = get_category_encoding_layer('pid', train_ds,
                                                      'int64', 5)
pid_encoding_layer(type_col)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [19]:
######################################################

In [20]:
batch_size = 256
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [21]:
all_inputs = []
encoded_features = []

# Numeric features.
for header in ['pid']:
  numeric_col = tf.keras.Input(shape=(1,), name=header)
  normalization_layer = get_normalization_layer(header, train_ds)
  encoded_numeric_col = normalization_layer(numeric_col)
  all_inputs.append(numeric_col)
  encoded_features.append(encoded_numeric_col)

In [22]:
# Categorical features encoded as integers.
age_col = tf.keras.Input(shape=(1,), name='year', dtype='int64')
encoding_layer = get_category_encoding_layer('year', train_ds, dtype='int64',
                                             max_tokens=5)
encoded_age_col = encoding_layer(age_col)
all_inputs.append(age_col)
encoded_features.append(encoded_age_col)

In [23]:
# Categorical features encoded as string.
categorical_cols = ['title', 'authors', 'jconf']
for header in categorical_cols:
  categorical_col = tf.keras.Input(shape=(1,), name=header, dtype='string')
  encoding_layer = get_category_encoding_layer(header, train_ds, dtype='string',
                                               max_tokens=5)
  encoded_categorical_col = encoding_layer(categorical_col)
  all_inputs.append(categorical_col)
  encoded_features.append(encoded_categorical_col)

In [24]:
all_features = tf.keras.layers.concatenate(encoded_features)
x = tf.keras.layers.Dense(50, activation="relu")(all_features)
x = tf.keras.layers.Dropout(0.5)(x)
output = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(all_inputs, output)
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=["accuracy"])

In [25]:
# rankdir='LR' is used to make the graph horizontal.
tf.keras.utils.plot_model(model, show_shapes=True, rankdir="LR")

('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


In [26]:
model.fit(train_ds, epochs=10, validation_data=val_ds)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.6306 - accuracy: 0.1818 - val_loss: 1.0419 - val_accuracy: 0.3333
Epoch 2/10
1/1 [==============================] - 0s 46ms/step - loss: 0.5882 - accuracy: 0.1818 - val_loss: 0.9881 - val_accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 39ms/step - loss: 1.2475 - accuracy: 0.1364 - val_loss: 0.9350 - val_accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 39ms/step - loss: 0.4000 - accuracy: 0.1818 - val_loss: 0.8817 - val_accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 0s 41ms/step - loss: -0.0856 - accuracy: 0.1818 - val_loss: 0.8284 - val_accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 42ms/step - loss: 0.6381 - accuracy: 0.1364 - val_loss: 0.7750 - val_accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 40ms/step - loss: 0.4321 - accuracy: 0.1364 - val_loss: 0.7219 - val_accuracy: 0.3333
Epoch 8/10
1/1 [============

In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

1/1 [==============================] - 0s 25ms/step - loss: 0.4193 - accuracy: 0.2500
Accuracy 0.25


In [43]:
sample = {
    'title': 'Multivariate Integration Hypercubic Mesh Networks',
  'year': 1998,
  'authors': 'Elise de Doncker,Ajay K. Gupta',
  'jconf': 'Parallel Computing',
  'pid': 1034401,
}

input_dict = {name: tf.convert_to_tensor([value]) for name, value in sample.items()}
print(input_dict)
predictions = model.predict(input_dict)
# prob = tf.nn.sigmoid(predictions[0])

print(predictions)

{'title': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Multivariate Integration Hypercubic Mesh Networks'], dtype=object)>, 'year': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1998])>, 'authors': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Elise de Doncker,Ajay K. Gupta'], dtype=object)>, 'jconf': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Parallel Computing'], dtype=object)>, 'pid': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1034401])>}
[[0.13424955]]


## This is an early attempt to use a classifier

In [29]:
LABELS = [0, 1, 2, 3, 4, 5, 6, 7, 8]


In [30]:
classifier = tf.estimator.DNNClassifier(
    feature_columns=all_features,
    # Two hidden layers of 30 and 10 nodes respectively.
    hidden_units=[50, 50],
    # The model must choose between 3 classes.
    n_classes=len(LABELS)
#     ,activation_fn='relu',batch_norm=50
)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\KHADGA~1\\AppData\\Local\\Temp\\tmp55sajoec', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [31]:
# classifier.train(train_ds)
# model.fit(train_ds, epochs=10, validation_data=val_ds)

In [32]:
# def input_fn(features, labels, training=True, batch_size=256):
#     # Convert the inputs to a Dataset.
#     dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

#     # Shuffle and repeat if you are in training mode.
#     if training:
#         dataset = dataset.shuffle(1000).repeat()
    
#     return dataset.batch(batch_size)

In [34]:
# classifier.train(input_fn=lambda: input_fn(train, labels, training=True),
#     steps=5000)

In [37]:
def input_fn(features, training=True, batch_size=256):
    if training :
        dataset = df_to_dataset(train, batch_size=batch_size)
        dataset = dataset.shuffle(1000).repeat()
    return dataset.batch(batch_size)

In [38]:
classifier.train(input_fn=lambda: input_fn(train_ds, training=True),
    steps=5000)

RuntimeError: Attempting to capture an EagerTensor without building a function.