## Assignment 2
> Dept : DSE

> Name : Alli khadga Jyoth

> Roll.No : 19024

In [1]:
import numpy as np
from numpy import random as rd

### Excercise 1

In [2]:
#1
a = np.random.randint(0,100,10)
a

array([98, 28, 22, 21, 85, 37, 26, 43, 23, 12])

In [3]:
#2
a.mean(),a.std()

(39.5, 27.390691849604675)

In [4]:
#3
b = np.random.randint(0,100,10)
b

array([20, 87, 97, 56, 74, 37,  5, 98, 91, 31])

In [5]:
#4
c = a+b / 2
c

array([108. ,  71.5,  70.5,  49. , 122. ,  55.5,  28.5,  92. ,  68.5,
        27.5])

In [6]:
#5
d = np.random.rand(10)
d = d*100
d

array([47.99887991, 43.42434592,  9.54240186, 68.56476555, 86.80467827,
       63.56302631, 47.82886029,  6.18175587, 76.01594651, 78.29416548])

In [7]:
#6
d.mean(),d.std()

(52.82188259770309, 26.248357901786594)

In [8]:
#7
d.min(),d.max()

(6.181755874949435, 86.8046782666703)

### Excercise 2

In [11]:
#1
a = rd.randint(0,100,20)
a

array([80, 93, 34, 64, 75, 60, 38, 88, 37, 29, 21, 15, 45, 30, 78, 16, 59,
       57, 82, 45])

In [12]:
#2
a[a%2 ==0].max()

88

In [13]:
#3
a[a%2 !=0].mean()

47.6

In [14]:
#4
a[a%2 !=0][[0,-1]]    

array([93, 45])

In [19]:
#5
b = rd.rand(20)*1000
b

array([181.87831431, 574.78478242,  92.9108513 , 596.10407017,
       150.7844509 , 749.30024577, 934.37666222, 432.12752692,
       717.38641675, 830.10665974, 658.38886062, 451.77952089,
       853.16377513, 122.91428088, 719.32287006,  46.88994837,
       393.64643615, 776.47897991, 231.60510348, 378.74026965])

In [20]:
b[b<b.mean()]

array([181.87831431,  92.9108513 , 150.7844509 , 432.12752692,
       451.77952089, 122.91428088,  46.88994837, 393.64643615,
       231.60510348, 378.74026965])

In [21]:
b[b<(b.mean() - b.std())]

array([181.87831431,  92.9108513 , 150.7844509 , 122.91428088,
        46.88994837])

### Excercise 3

In [22]:
a = rd.randint(0,100,20)

In [28]:
b= a[a%2 ==0]
b[b>a.mean()].min()

72

In [36]:
a[(a<(a.mean()-a.std()))|(a>(a.mean()+a.std()))]

array([16, 80, 80,  0, 83,  0, 87])

In [52]:
a[(a%2 !=0) & (a<a.mean()) |(a%2 ==0) & (a>a.mean()) ]

array([80, 23, 72, 27, 80, 49])

 ### Excercise 4

In [67]:
a = rd.randint(0,100,40)

In [68]:
a.mean(),a.std()

(63.225, 26.8677199442007)

In [69]:
a[(a>(a.mean()-a.std())) | (a<(a.mean()+a.std()))]=a.mean()
a,a.mean(),a.std()

(array([63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
        63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
        63, 63, 63, 63, 63, 63]),
 63.0,
 0.0)

In [72]:
b = rd.randint(0,100,10)
b

array([82, 71, 56, 70, 92, 21, 88, 10, 21, 75])

In [75]:
b[::2] = b[1::2]
b

array([71, 71, 70, 70, 21, 21, 10, 10, 75, 75])

### Excercise 5

In [107]:
a = rd.randint(0,100,10)

In [108]:
a.mean(),a.std()

(62.7, 22.378784596130327)

In [114]:
b=  rd.normal(loc = a.mean(),scale = a.std(),size=20)
b,b.mean(),b.std()

(array([ 86.81679217,  44.7028305 ,  54.41904521,  96.28226773,
         89.82042734,  15.16748916, 105.86397474, 114.43770853,
         81.00482139,  87.1803689 ,  92.7757234 ,  81.20467773,
         91.82533112,  88.7372661 ,  76.82390496,  63.97503232,
         62.95068373,  59.50129423,  75.08617714,  62.54080969]),
 76.55583130397144,
 22.214133838101407)

In [115]:
b[(b<(b.mean()-b.std())) | (b> (b.mean()+b.std()))] = b.mean()
b,b.mean(),b.std()

(array([86.81679217, 76.5558313 , 54.41904521, 96.28226773, 89.82042734,
        76.5558313 , 76.5558313 , 76.5558313 , 81.00482139, 87.1803689 ,
        92.7757234 , 81.20467773, 91.82533112, 88.7372661 , 76.82390496,
        63.97503232, 62.95068373, 59.50129423, 75.08617714, 62.54080969]),
 77.85839741898424,
 11.743668864963244)

In [111]:
c = rd.rand(20)*100
c,c.mean()

(array([ 8.26669856, 30.62727192, 34.52582286, 75.39856345, 90.38244167,
        57.95546145, 94.64138412, 57.94791705, 73.66140412, 78.13829832,
         8.97803684, 74.16742763, 16.07064585, 67.3328988 , 53.80535509,
        24.09334087,  5.36999357, 71.6793736 , 91.09855926, 17.00159747]),
 51.557124625318124)

In [112]:
c[c.astype('int') %2 ==0] = c.mean()
c

array([51.55712463, 51.55712463, 51.55712463, 75.39856345, 51.55712463,
       57.95546145, 51.55712463, 57.94791705, 73.66140412, 51.55712463,
       51.55712463, 51.55712463, 51.55712463, 67.3328988 , 53.80535509,
       51.55712463,  5.36999357, 71.6793736 , 91.09855926, 17.00159747])

### Excercise 6

In [187]:
a = rd.randint(0,1000,30)
b = a.astype(np.float64)

In [188]:
b[(b<(b.mean()-b.std())) | (b> (b.mean()+b.std()))] = None
b

array([273., 633., 261.,  nan, 576., 246., 614.,  nan, 233.,  nan, 532.,
        nan, 298.,  nan, 639.,  nan, 330.,  nan, 264., 500.,  nan,  nan,
        nan, 525.,  nan, 628., 204., 331., 229., 653.])

In [199]:
b[np.isnan(b)] = b[~np.isnan(b)].mean()
b

array([273.        , 633.        , 261.        , 419.42105263,
       576.        , 246.        , 614.        , 419.42105263,
       233.        , 419.42105263, 532.        , 419.42105263,
       298.        , 419.42105263, 639.        , 419.42105263,
       330.        , 419.42105263, 264.        , 500.        ,
       419.42105263, 419.42105263, 419.42105263, 525.        ,
       419.42105263, 628.        , 204.        , 331.        ,
       229.        , 653.        ])

### Excercise 7

In [266]:
a = rd.randint(0,100,(45,45))
a

array([[71, 70, 84, ..., 86, 18, 14],
       [91, 60, 61, ..., 17, 45, 42],
       [ 4, 28, 68, ..., 58,  1, 63],
       ...,
       [35, 92, 38, ..., 35,  7, 41],
       [94, 68, 86, ..., 41, 59, 92],
       [33,  4, 86, ..., 81, 28,  2]])

In [267]:
a[2]

array([ 4, 28, 68, 65, 48, 12, 88, 87, 96, 15, 92, 60, 83,  9, 62, 47, 41,
       76, 86, 43, 88, 79, 10, 94, 10, 26, 53, 47, 92, 19,  4, 10, 89, 21,
       64, 11, 29, 31, 12, 89, 99, 30, 58,  1, 63])

In [268]:
a[:,3]

array([88, 52, 65, 61, 62, 58, 96, 85, 74, 75, 89, 63, 69, 13, 24, 47, 19,
       15, 16, 74, 80, 80, 63, 97, 15, 26, 46, 19, 83, 53, 84, 45, 80, 46,
       31, 55, 20, 57, 54, 77, 36, 21, 33, 85, 86])

In [269]:
a[[1,4]]

array([[91, 60, 61, 52, 55, 88, 17, 89, 61, 16, 36, 32, 89,  2, 25, 83,
        19, 92, 14, 15, 77,  2, 97, 16, 34, 15, 70, 42,  1, 60, 95, 68,
        38,  3, 83, 26, 27, 22, 80, 97, 19, 82, 17, 45, 42],
       [37, 26, 86, 62, 56, 43, 19, 62, 67, 25, 19, 16, 83, 28, 51, 73,
         0, 30, 62, 88, 32, 85, 36, 22, 46, 91, 83, 38, 90, 80, 31, 37,
        90, 79, 29, 37, 13, 77, 92, 22, 37, 77, 86, 57, 93]])

In [270]:
a[:,[1,4]]

array([[70,  5],
       [60, 55],
       [28, 48],
       [74, 91],
       [26, 56],
       [89, 69],
       [ 5, 72],
       [83, 73],
       [12, 17],
       [79, 58],
       [42, 43],
       [ 3, 92],
       [ 8, 64],
       [50, 83],
       [80, 56],
       [88, 82],
       [15, 75],
       [39, 94],
       [33, 78],
       [78, 84],
       [34, 48],
       [16,  1],
       [81, 24],
       [54, 53],
       [12, 95],
       [53, 79],
       [97, 69],
       [92,  2],
       [10, 29],
       [58, 23],
       [32, 34],
       [51, 18],
       [44, 66],
       [23, 69],
       [31,  4],
       [12, 56],
       [41, 28],
       [82, 46],
       [67, 64],
       [ 8,  5],
       [73, 64],
       [67, 44],
       [92, 26],
       [68, 43],
       [ 4, 79]])

In [271]:
a[4][a[4]%2 == 0].mean()

52.27272727272727

In [272]:
a[:,4][a[:,4]%2 !=0].mean()

52.8

### Excercise 8

In [273]:
a = rd.randint(0,100,[6,6])
a

array([[69, 87, 33, 69, 32, 92],
       [18,  4, 30, 77, 89, 92],
       [ 8, 48,  1, 37, 77, 60],
       [76, 77, 50, 52,  7,  0],
       [82, 86, 34, 41, 23, 62],
       [79, 84, 16, 86, 25, 27]])

In [274]:
a.mean(axis = 0)

array([55.33333333, 64.33333333, 27.33333333, 60.33333333, 42.16666667,
       55.5       ])

In [275]:
a[a%2 ==0] = a[a%2 ==0]*2
a

array([[ 69,  87,  33,  69,  64, 184],
       [ 36,   8,  60,  77,  89, 184],
       [ 16,  96,   1,  37,  77, 120],
       [152,  77, 100, 104,   7,   0],
       [164, 172,  68,  41,  23, 124],
       [ 79, 168,  32, 172,  25,  27]])

In [276]:
a.mean(axis = 0)

array([ 86.        , 101.33333333,  49.        ,  83.33333333,
        47.5       , 106.5       ])

In [277]:
a = a.transpose()
a,a.mean(axis = 1)

(array([[ 69,  36,  16, 152, 164,  79],
        [ 87,   8,  96,  77, 172, 168],
        [ 33,  60,   1, 100,  68,  32],
        [ 69,  77,  37, 104,  41, 172],
        [ 64,  89,  77,   7,  23,  25],
        [184, 184, 120,   0, 124,  27]]),
 array([ 86.        , 101.33333333,  49.        ,  83.33333333,
         47.5       , 106.5       ]))

In [278]:
a.sort(axis = 0)
a

array([[ 33,   8,   1,   0,  23,  25],
       [ 64,  36,  16,   7,  41,  27],
       [ 69,  60,  37,  77,  68,  32],
       [ 69,  77,  77, 100, 124,  79],
       [ 87,  89,  96, 104, 164, 168],
       [184, 184, 120, 152, 172, 172]])